### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [adnryha/grid__template#1]
1)
Ваша работа содержит невалидный код (невалидный - означает несоответствие стандартам HTML, другими словами - код с критическими ошибками).
Все файлы проекта, без исключения, должны проходить валидацию.
HTML валидатор... https://validator.w3.org/#validate_by_input
  CSS валидатор... https://jigsaw.w3.org/css-validator/#validate_by_upload

![image](https://user-images.githubusercontent.com/8464662/142736588-aa4a5825-0235-486e-848d-660afb7f76bf.png)

2)

Ваша работа содержит невалидный код (невалидный - означает несоответствие стандартам CSS, другими словами - код с критическими ошибками).
Все файлы проекта, без исключения, должны проходить валидацию.
HTML валидатор... https://validator.w3.org/#validate_by_input
  CSS валидатор... https://jigsaw.w3.org/css-validator/#validate_by_upload

![image](https://user-images.githubusercontent.com/8464662/142736602-c3943c41-af43-49e7-b865-af14a4033ec4.png)

**Comment by adnryha** [comment]
Выполнил валидацию CSS кода.
![image](https://user-images.githubusercontent.com/93428312/142739640-bc8a538d-2c5d-46d6-97e4-15000e352d1f.png)

**Comment by adnryha** [comment]
Выполнил валидацию HTML кода.
Есть два предупреждения от валидатора, считаю, что ними возможно пренебречь
![image](https://user-images.githubusercontent.com/93428312/142739739-69f47198-cb7e-4a37-b53d-4a692d921696.png)

**Comment by Alecto** [comment]
3)
Внешний вид заполнителей и текста не соответствует макету.
![image](https://user-images.githubusercontent.com/8464662/142752633-63e91edf-364d-4715-8488-87e2183ec56e.png)

**Comment by adnryha** [comment]
Выполнил правки для input.
 https://adnryha.github.io/grid__template/
![image](https://user-images.githubusercontent.com/93428312/142772041-658879a4-ab76-4c6c-a47e-a02296ea78eb.png)

**Comment by Alecto** [comment]
3 - не исправлено
![image](https://user-images.githubusercontent.com/8464662/142825966-7673f0c3-b72f-4b53-b489-5d5bd9412c89.png)

**Comment by adnryha** [comment]
Исправлено
мой проект:
![image](https://user-images.githubusercontent.com/93428312/142912499-5fdbe3bb-ccaa-4b43-89fb-e5151c14cfbf.png)
Мастер макет:
![Screenshot_2](https://user-images.githubusercontent.com/93428312/142913299-d4ea18b5-9462-4971-92ca-94f73ae1edfc.jpg)

**Comment by Alecto** [comment]
на этой кнопке анимация срабатывает только при уходе мышки
![image](https://user-images.githubusercontent.com/8464662/142977243-80e4e36b-8a4a-41e4-ae6f-e5b30523935e.png)
